name: build

on:
  push:
    branches:
      - main
      - reimagied

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-win
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: .\setup.bat
    - run: ./pack.sh -p Windows
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-pamenpletary-normal-windows
        path: ./build/Windows/temp
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./pack.sh
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-pamenpletary-normal-android
        path: ./build/Android/temp
  ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./build.sh -p iOS
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-pamenpletary-normal-ios-materials
        path: ./build/iOS
  ios-pack:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./pack.sh -p iOS
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-pamenpletary-normal-ios-pack
        path: ./build/iOS/temp
